name: Airbase CI/CD

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to destroy (used for stop_review job)'
        required: false
        type: string

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package for Airbase
        run: |
          zip -r airbase.zip . -i build

      - name: Deploy
        run: npx @airbase/airbase-cli deploy --output deploy.env --yes
        env:
          DYNAMIC_ENVIRONMENT_URL: ${{ env.DYNAMIC_ENVIRONMENT_URL }}

      - name: Production Environment Info
        run: echo "Production environment deployed at $DYNAMIC_ENVIRONMENT_URL"
        env:
          DYNAMIC_ENVIRONMENT_URL: ${{ env.DYNAMIC_ENVIRONMENT_URL }}


  review:
    name: Deploy Review Environment
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package for Airbase
        run: |
          zip -r airbase.zip . -i build

      - name: Deploy Review
        run: npx @airbase/airbase-cli deploy --output deploy.env --yes
        env:
          DYNAMIC_ENVIRONMENT_URL: ${{ env.DYNAMIC_ENVIRONMENT_URL }}
          CI_COMMIT_REF_SLUG: ${{ github.ref_name }}

      - name: Save Airbase Link Artifact
        run: |
          mkdir -p .airbase
          echo '{"environment": "${{ github.ref_name }}"}' > .airbase/airbase.link.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: airbase-link
          path: .airbase/airbase.link.json


  stop_review:
    name: Stop Review Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.branch != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Stop Review
        run: npx @airbase/airbase-cli destroy "$CI_COMMIT_REF_SLUG" --yes
        env:
          CI_COMMIT_REF_SLUG: ${{ github.event.inputs.branch }}
